# Generated by Django 4.2.5 on 2023-09-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
