# Generated by Django 4.2.5 on 2023-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Traveller', 'Traveller'), ('Driver', 'Driver'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
