# Generated by Django 4.2.5 on 2023-10-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Traveller', 'Traveller'), ('Driver', 'Driver')], max_length=20),
        ),
    ]
