# Generated by Django 4.2.5 on 2024-02-19 05:42

import Niwi_Travels.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0026_custompackage_status_custompassenger_custombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='boarding',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='passenger_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, validators=[Niwi_Travels.models.validate_start_date]),
        ),
        migrations.AlterField(
            model_name='custompassenger',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Niwi_Travels.custompackage'),
        ),
    ]
