# Generated by Django 4.2.5 on 2024-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0027_alter_custombooking_boarding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='status',
            field=models.CharField(choices=[('Post', 'Post'), ('Save', 'Save')], max_length=10),
        ),
    ]
