# Generated by Django 4.2.5 on 2024-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niwi_Travels', '0028_alter_custompackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='boarding',
            field=models.CharField(choices=[('Trivandrum_Central', 'Trivandrum Central'), ('Kazhakuttam', 'Kazhakuttam'), ('Neyyattinkara', 'Neyyattinkara'), ('Ernakulam', 'Ernakulam Junction'), ('Kochi_Central', 'Kochi Airport'), ('Aluva', 'Aluva Railway Station'), ('Kakkanad', 'Kakkanad'), ('Kozhikode_Central', 'Kozhikode Central'), ('Calicut_Airport', 'Calicut Airport'), ('Vadakara', 'Vadakara'), ('Kannur_Central', 'Kannur Airport'), ('Thalassery', 'Thalassery'), ('Payyannur', 'Payyannur'), ('Kollam_Central', 'Kollam Central'), ('Karunagappally', 'Karunagappally'), ('Punalur', 'Punalur'), ('Palakkad_Central', 'Palakkad Central'), ('Ottapalam', 'Ottapalam'), ('Chittur', 'Chittur'), ('Thrissur_Central', 'Thrissur Central'), ('Kodungallur', 'Kodungallur'), ('Chalakudy', 'Chalakudy'), ('Alappuzha_Central', 'Alappuzha Central'), ('Ambalappuzha', 'Ambalappuzha'), ('Cherthala', 'Cherthala'), ('Kottayam_Central', 'Kottayam Central'), ('Changanassery', 'Changanassery'), ('Vaikom', 'Vaikom'), ('Pathanamthitta_Central', 'Pathanamthitta Central'), ('Adoor', 'Adoor'), ('Thiruvalla', 'Thiruvalla'), ('Malappuram_Central', 'Malappuram Central'), ('Manjeri', 'Manjeri'), ('Perinthalmanna', 'Perinthalmanna'), ('Idukki_Central', 'Idukki Central'), ('Thodupuzha', 'Thodupuzha'), ('Munnar', 'Munnar'), ('Kasaragod_Central', 'Kasaragod Central'), ('Kanhangad', 'Kanhangad'), ('Kasaragod_Town', 'Kasaragod Town'), ('Wayanad_Central', 'Wayanad Central'), ('Kalpetta', 'Kalpetta'), ('Mananthavady', 'Mananthavady')], max_length=50),
        ),
    ]
